import type { ThemeHex } from '@/hooks/use-theme';

export interface ThemePreset {
    name: string;
    colors: ThemeHex;
}

export const defaultTheme: ThemePreset = {
    name: "Padrão (Escuro)",
    colors: {
        background: '#191A1B',
        foreground: '#FAFAFA',
        card: '#131415',
        cardForeground: '#FAFAFA',
        popover: '#0F1011',
        popoverForeground: '#FAFAFA',
        primary: '#4EE1A0',
        primaryForeground: '#F6FEFB',
        secondary: '#242627',
        secondaryForeground: '#FAFAFA',
        muted: '#242627',
        mutedForeground: '#A3A6A8',
        accent: '#242627',
        accentForeground: '#FAFAFA',
        destructive: '#7F1D1D',
        destructiveForeground: '#FAFAFA',
        border: '#3F4144',
        input: '#242627',
        ring: '#4EE1A0',
        cacambaForeground: '#FAFAFA',
        accentPrice: '#FBBF24',
    }
};

export const themes: ThemePreset[] = [
    defaultTheme,
    {
        name: "Neve (Claro)",
        colors: {
            background: '#F9FAFB',
            foreground: '#111827',
            card: '#FFFFFF',
            cardForeground: '#111827',
            popover: '#FFFFFF',
            popoverForeground: '#111827',
            primary: '#2563EB',
            primaryForeground: '#FFFFFF',
            secondary: '#F3F4F6',
            secondaryForeground: '#111827',
            muted: '#F3F4F6',
            mutedForeground: '#6B7280',
            accent: '#F3F4F6',
            accentForeground: '#111827',
            destructive: '#DC2626',
            destructiveForeground: '#FFFFFF',
            border: '#E5E7EB',
            input: '#FFFFFF',
            ring: '#2563EB',
            cacambaForeground: '#111827',
            accentPrice: '#F59E0B',
        }
    },
    {
        name: "Cyberpunk Neon",
        colors: {
            background: '#0d0221',
            foreground: '#f0f0f0',
            card: '#1a0c36',
            cardForeground: '#f0f0f0',
            popover: '#100529',
            popoverForeground: '#f0f0f0',
            primary: '#00f6ff',
            primaryForeground: '#0d0221',
            secondary: '#241440',
            secondaryForeground: '#f0f0f0',
            muted: '#241440',
            mutedForeground: '#a09ca8',
            accent: '#ff00ff',
            accentForeground: '#f0f0f0',
            destructive: '#ff003c',
            destructiveForeground: '#0d0221',
            border: '#3c2b5c',
            input: '#241440',
            ring: '#00f6ff',
            cacambaForeground: '#00f6ff',
            accentPrice: '#ff00ff',
        }
    },
    {
        name: "Menta Fresca",
        colors: {
            background: '#f0fdf4',
            foreground: '#1e293b',
            card: '#ffffff',
            cardForeground: '#1e293b',
            popover: '#ffffff',
            popoverForeground: '#1e293b',
            primary: '#10b981',
            primaryForeground: '#ffffff',
            secondary: '#ecfdf5',
            secondaryForeground: '#1e293b',
            muted: '#f1f5f9',
            mutedForeground: '#64748b',
            accent: '#d1fae5',
            accentForeground: '#065f46',
            destructive: '#ef4444',
            destructiveForeground: '#ffffff',
            border: '#e2e8f0',
            input: '#ffffff',
            ring: '#10b981',
            cacambaForeground: '#065f46',
            accentPrice: '#f59e0b',
        }
    },
    {
        name: "Oceano Profundo",
        colors: {
            background: '#0f172a',
            foreground: '#f1f5f9',
            card: '#1e293b',
            cardForeground: '#f1f5f9',
            popover: '#0f172a',
            popoverForeground: '#f1f5f9',
            primary: '#38bdf8',
            primaryForeground: '#0f172a',
            secondary: '#334155',
            secondaryForeground: '#f1f5f9',
            muted: '#334155',
            mutedForeground: '#94a3b8',
            accent: '#475569',
            accentForeground: '#f1f5f9',
            destructive: '#f43f5e',
            destructiveForeground: '#f1f5f9',
            border: '#334155',
            input: '#334155',
            ring: '#38bdf8',
            cacambaForeground: '#38bdf8',
            accentPrice: '#fbbf24',
        }
    },
    {
        name: "Outono Aconchegante",
        colors: {
            background: '#2a1a1f',
            foreground: '#f3e5e1',
            card: '#3b2a2f',
            cardForeground: '#f3e5e1',
            popover: '#25151a',
            popoverForeground: '#f3e5e1',
            primary: '#f97316',
            primaryForeground: '#ffffff',
            secondary: '#4d3a3f',
            secondaryForeground: '#f3e5e1',
            muted: '#4d3a3f',
            mutedForeground: '#c4b5b1',
            accent: '#6b5a5f',
            accentForeground: '#f3e5e1',
            destructive: '#ef4444',
            destructiveForeground: '#ffffff',
            border: '#4d3a3f',
            input: '#4d3a3f',
            ring: '#f97316',
            cacambaForeground: '#f97316',
            accentPrice: '#eab308',
        }
    },
    {
        name: "Lavanda Suave",
        colors: {
            background: '#f5f3ff',
            foreground: '#2e1065',
            card: '#ffffff',
            cardForeground: '#2e1065',
            popover: '#ede9fe',
            popoverForeground: '#2e1065',
            primary: '#8b5cf6',
            primaryForeground: '#ffffff',
            secondary: '#ede9fe',
            secondaryForeground: '#4c1d95',
            muted: '#ddd6fe',
            mutedForeground: '#5b21b6',
            accent: '#c4b5fd',
            accentForeground: '#3730a3',
            destructive: '#ec4899',
            destructiveForeground: '#ffffff',
            border: '#ddd6fe',
            input: '#ffffff',
            ring: '#8b5cf6',
            cacambaForeground: '#5b21b6',
            accentPrice: '#f59e0b',
        }
    },
    {
        name: "Grafite Industrial",
        colors: {
            background: '#18181b',
            foreground: '#fafafa',
            card: '#27272a',
            cardForeground: '#fafafa',
            popover: '#18181b',
            popoverForeground: '#fafafa',
            primary: '#fafafa',
            primaryForeground: '#18181b',
            secondary: '#3f3f46',
            secondaryForeground: '#fafafa',
            muted: '#3f3f46',
            mutedForeground: '#a1a1aa',
            accent: '#52525b',
            accentForeground: '#fafafa',
            destructive: '#ef4444',
            destructiveForeground: '#fafafa',
            border: '#3f3f46',
            input: '#3f3f46',
            ring: '#fafafa',
            cacambaForeground: '#fafafa',
            accentPrice: '#facc15',
        }
    },
    {
        name: "Céu de Verão",
        colors: {
            background: '#f0f9ff',
            foreground: '#0c4a6e',
            card: '#ffffff',
            cardForeground: '#0c4a6e',
            popover: '#e0f2fe',
            popoverForeground: '#0c4a6e',
            primary: '#0ea5e9',
            primaryForeground: '#ffffff',
            secondary: '#e0f2fe',
            secondaryForeground: '#0891b2',
            muted: '#bae6fd',
            mutedForeground: '#0369a1',
            accent: '#7dd3fc',
            accentForeground: '#0c4a6e',
            destructive: '#f43f5e',
            destructiveForeground: '#ffffff',
            border: '#bae6fd',
            input: '#ffffff',
            ring: '#0ea5e9',
            cacambaForeground: '#0369a1',
            accentPrice: '#f97316',
        }
    },
    {
        name: "Drácula",
        colors: {
            background: '#282a36',
            foreground: '#f8f8f2',
            card: '#44475a',
            cardForeground: '#f8f8f2',
            popover: '#282a36',
            popoverForeground: '#f8f8f2',
            primary: '#bd93f9',
            primaryForeground: '#282a36',
            secondary: '#6272a4',
            secondaryForeground: '#f8f8f2',
            muted: '#6272a4',
            mutedForeground: '#f8f8f2',
            accent: '#ff79c6',
            accentForeground: '#282a36',
            destructive: '#ff5555',
            destructiveForeground: '#f8f8f2',
            border: '#6272a4',
            input: '#44475a',
            ring: '#bd93f9',
            cacambaForeground: '#50fa7b',
            accentPrice: '#f1fa8c',
        }
    },
    {
        name: "Rosa Quartzo",
        colors: {
            background: '#fff1f2',
            foreground: '#500724',
            card: '#ffffff',
            cardForeground: '#500724',
            popover: '#ffe4e6',
            popoverForeground: '#500724',
            primary: '#ec4899',
            primaryForeground: '#ffffff',
            secondary: '#fce7f3',
            secondaryForeground: '#831843',
            muted: '#fbcfe8',
            mutedForeground: '#9d174d',
            accent: '#f9a8d4',
            accentForeground: '#500724',
            destructive: '#e11d48',
            destructiveForeground: '#ffffff',
            border: '#fbcfe8',
            input: '#ffffff',
            ring: '#ec4899',
            cacambaForeground: '#9d174d',
            accentPrice: '#f59e0b',
        }
    },
    {
        name: "Matrix",
        colors: {
            background: '#000000',
            foreground: '#00ff00',
            card: '#0a0a0a',
            cardForeground: '#00ff00',
            popover: '#000000',
            popoverForeground: '#00ff00',
            primary: '#00ff00',
            primaryForeground: '#000000',
            secondary: '#0f0f0f',
            secondaryForeground: '#00ff00',
            muted: '#1a1a1a',
            mutedForeground: '#008000',
            accent: '#1f1f1f',
            accentForeground: '#00ff00',
            destructive: '#ff0000',
            destructiveForeground: '#000000',
            border: '#003300',
            input: '#0a0a0a',
            ring: '#00ff00',
            cacambaForeground: '#ffffff',
            accentPrice: '#00ff00',
        }
    },
    {
        name: "Café Expresso",
        colors: {
            background: '#1c1611',
            foreground: '#d4c5b0',
            card: '#2c221a',
            cardForeground: '#d4c5b0',
            popover: '#16110e',
            popoverForeground: '#d4c5b0',
            primary: '#a67b5b',
            primaryForeground: '#1c1611',
            secondary: '#403229',
            secondaryForeground: '#d4c5b0',
            muted: '#403229',
            mutedForeground: '#8c7e6a',
            accent: '#594639',
            accentForeground: '#d4c5b0',
            destructive: '#993d3d',
            destructiveForeground: '#d4c5b0',
            border: '#403229',
            input: '#2c221a',
            ring: '#a67b5b',
            cacambaForeground: '#a67b5b',
            accentPrice: '#d97706',
        }
    },
    {
        name: "Areia do Deserto (Claro)",
        colors: {
            background: '#fdf6e3',
            foreground: '#657b83',
            card: '#f6efd5',
            cardForeground: '#586e75',
            popover: '#eee8d5',
            popoverForeground: '#586e75',
            primary: '#268bd2',
            primaryForeground: '#ffffff',
            secondary: '#eee8d5',
            secondaryForeground: '#586e75',
            muted: '#eee8d5',
            mutedForeground: '#839496',
            accent: '#d3cbb7',
            accentForeground: '#073642',
            destructive: '#dc322f',
            destructiveForeground: '#ffffff',
            border: '#eee8d5',
            input: '#fdf6e3',
            ring: '#268bd2',
            cacambaForeground: '#073642',
            accentPrice: '#b58900',
        }
    },
    {
        name: "Floresta Sombria",
        colors: {
            background: '#1a202c',
            foreground: '#e2e8f0',
            card: '#2d3748',
            cardForeground: '#e2e8f0',
            popover: '#1a202c',
            popoverForeground: '#e2e8f0',
            primary: '#48bb78',
            primaryForeground: '#1a202c',
            secondary: '#4a5568',
            secondaryForeground: '#e2e8f0',
            muted: '#4a5568',
            mutedForeground: '#a0aec0',
            accent: '#718096',
            accentForeground: '#e2e8f0',
            destructive: '#e53e3e',
            destructiveForeground: '#e2e8f0',
            border: '#4a5568',
            input: '#2d3748',
            ring: '#48bb78',
            cacambaForeground: '#68d391',
            accentPrice: '#f6ad55',
        }
    },
    {
        name: "Pêssego e Creme",
        colors: {
            background: '#fff7f0',
            foreground: '#432818',
            card: '#ffffff',
            cardForeground: '#432818',
            popover: '#ffeadb',
            popoverForeground: '#432818',
            primary: '#ff8a5b',
            primaryForeground: '#432818',
            secondary: '#ffeadb',
            secondaryForeground: '#432818',
            muted: '#fdeadd',
            mutedForeground: '#995a3b',
            accent: '#fddfc8',
            accentForeground: '#432818',
            destructive: '#ef4444',
            destructiveForeground: '#ffffff',
            border: '#fddfc8',
            input: '#ffffff',
            ring: '#ff8a5b',
            cacambaForeground: '#995a3b',
            accentPrice: '#f59e0b',
        }
    },
    {
        name: "Ártico (Claro)",
        colors: {
            background: '#f9fafb',
            foreground: '#1f2937',
            card: '#ffffff',
            cardForeground: '#1f2937',
            popover: '#f3f4f6',
            popoverForeground: '#1f2937',
            primary: '#3b82f6',
            primaryForeground: '#ffffff',
            secondary: '#e5e7eb',
            secondaryForeground: '#1f2937',
            muted: '#f3f4f6',
            mutedForeground: '#6b7280',
            accent: '#dbeafe',
            accentForeground: '#1e40af',
            destructive: '#ef4444',
            destructiveForeground: '#ffffff',
            border: '#d1d5db',
            input: '#ffffff',
            ring: '#3b82f6',
            cacambaForeground: '#1e3a8a',
            accentPrice: '#f59e0b',
        }
    },
    {
        name: "Vampiro",
        colors: {
            background: '#1d1f21',
            foreground: '#c5c8c6',
            card: '#282a2e',
            cardForeground: '#c5c8c6',
            popover: '#1d1f21',
            popoverForeground: '#c5c8c6',
            primary: '#cc6666',
            primaryForeground: '#1d1f21',
            secondary: '#373b41',
            secondaryForeground: '#c5c8c6',
            muted: '#373b41',
            mutedForeground: '#969896',
            accent: '#b294bb',
            accentForeground: '#1d1f21',
            destructive: '#a54242',
            destructiveForeground: '#c5c8c6',
            border: '#373b41',
            input: '#282a2e',
            ring: '#cc6666',
            cacambaForeground: '#81a2be',
            accentPrice: '#f0c674',
        }
    },
    {
        name: "Cítrico",
        colors: {
            background: '#f7fee7',
            foreground: '#365314',
            card: '#ffffff',
            cardForeground: '#365314',
            popover: '#f0fdf4',
            popoverForeground: '#365314',
            primary: '#84cc16',
            primaryForeground: '#365314',
            secondary: '#dcfce7',
            secondaryForeground: '#365314',
            muted: '#ecfccb',
            mutedForeground: '#4d7c0f',
            accent: '#d9f99d',
            accentForeground: '#365314',
            destructive: '#ef4444',
            destructiveForeground: '#ffffff',
            border: '#d9f99d',
            input: '#ffffff',
            ring: '#84cc16',
            cacambaForeground: '#4d7c0f',
            accentPrice: '#f59e0b',
        }
    },
    {
        name: "Ardósia Escura",
        colors: {
            background: '#020617',
            foreground: '#e2e8f0',
            card: '#0f172a',
            cardForeground: '#e2e8f0',
            popover: '#020617',
            popoverForeground: '#e2e8f0',
            primary: '#f8fafc',
            primaryForeground: '#020617',
            secondary: '#1e293b',
            secondaryForeground: '#e2e8f0',
            muted: '#1e293b',
            mutedForeground: '#94a3b8',
            accent: '#334155',
            accentForeground: '#e2e8f0',
            destructive: '#be123c',
            destructiveForeground: '#e2e8f0',
            border: '#1e293b',
            input: '#0f172a',
            ring: '#f8fafc',
            cacambaForeground: '#64748b',
            accentPrice: '#ca8a04',
        }
    },
    {
        name: "Abelha",
        colors: {
            background: '#fffbeb',
            foreground: '#422006',
            card: '#ffffff',
            cardForeground: '#422006',
            popover: '#fef3c7',
            popoverForeground: '#422006',
            primary: '#f59e0b',
            primaryForeground: '#422006',
            secondary: '#fef3c7',
            secondaryForeground: '#422006',
            muted: '#fef9c3',
            mutedForeground: '#78350f',
            accent: '#fde68a',
            accentForeground: '#422006',
            destructive: '#ef4444',
            destructiveForeground: '#ffffff',
            border: '#fde68a',
            input: '#ffffff',
            ring: '#f59e0b',
            cacambaForeground: '#78350f',
            accentPrice: '#ea580c',
        }
    },
    {
        name: "Tokio Night",
        colors: {
            background: '#1a1b26',
            foreground: '#a9b1d6',
            card: '#24283b',
            cardForeground: '#a9b1d6',
            popover: '#1f2335',
            popoverForeground: '#a9b1d6',
            primary: '#7aa2f7',
            primaryForeground: '#1a1b26',
            secondary: '#414868',
            secondaryForeground: '#a9b1d6',
            muted: '#414868',
            mutedForeground: '#565f89',
            accent: '#bb9af7',
            accentForeground: '#1a1b26',
            destructive: '#f7768e',
            destructiveForeground: '#1a1b26',
            border: '#414868',
            input: '#24283b',
            ring: '#7aa2f7',
            cacambaForeground: '#e0af68',
            accentPrice: '#ff9e64',
        }
    },
    {
        name: "Material You (Claro)",
        colors: {
            background: '#fffbfe',
            foreground: '#1c1b1f',
            card: '#f4eff4',
            cardForeground: '#1c1b1f',
            popover: '#e8e0e9',
            popoverForeground: '#1c1b1f',
            primary: '#6750a4',
            primaryForeground: '#ffffff',
            secondary: '#e8def8',
            secondaryForeground: '#1d192b',
            muted: '#e8e0e9',
            mutedForeground: '#49454f',
            accent: '#fddd82',
            accentForeground: '#1c1b1f',
            destructive: '#b3261e',
            destructiveForeground: '#ffffff',
            border: '#cac4d0',
            input: '#f4eff4',
            ring: '#6750a4',
            cacambaForeground: '#4a4458',
            accentPrice: '#7d5260',
        }
    },
    {
        name: "Material You (Escuro)",
        colors: {
            background: '#1c1b1f',
            foreground: '#e6e1e5',
            card: '#2b2930',
            cardForeground: '#e6e1e5',
            popover: '#25232a',
            popoverForeground: '#e6e1e5',
            primary: '#d0bcff',
            primaryForeground: '#381e72',
            secondary: '#ccc2dc',
            secondaryForeground: '#332d41',
            muted: '#312d35',
            mutedForeground: '#958f99',
            accent: '#fddd82',
            accentForeground: '#3e2e00',
            destructive: '#f2b8b5',
            destructiveForeground: '#601410',
            border: '#49454f',
            input: '#2b2930',
            ring: '#d0bcff',
            cacambaForeground: '#cac4d0',
            accentPrice: '#f7b1b0',
        }
    },
    {
        name: "Nord",
        colors: {
            background: '#2e3440',
            foreground: '#d8dee9',
            card: '#3b4252',
            cardForeground: '#d8dee9',
            popover: '#2e3440',
            popoverForeground: '#d8dee9',
            primary: '#88c0d0',
            primaryForeground: '#2e3440',
            secondary: '#434c5e',
            secondaryForeground: '#d8dee9',
            muted: '#4c566a',
            mutedForeground: '#d8dee9',
            accent: '#81a1c1',
            accentForeground: '#2e3440',
            destructive: '#bf616a',
            destructiveForeground: '#d8dee9',
            border: '#4c566a',
            input: '#3b4252',
            ring: '#88c0d0',
            cacambaForeground: '#a3be8c',
            accentPrice: '#ebcb8b',
        }
    },
    {
        name: "Aurora",
        colors: {
            background: '#f9fafa',
            foreground: '#374151',
            card: '#ffffff',
            cardForeground: '#374151',
            popover: '#ffffff',
            popoverForeground: '#374151',
            primary: '#6366f1',
            primaryForeground: '#ffffff',
            secondary: '#f3f4f6',
            secondaryForeground: '#374151',
            muted: '#e5e7eb',
            mutedForeground: '#6b7280',
            accent: '#eef2ff',
            accentForeground: '#4338ca',
            destructive: '#ef4444',
            destructiveForeground: '#ffffff',
            border: '#e5e7eb',
            input: '#ffffff',
            ring: '#6366f1',
            cacambaForeground: '#4f46e5',
            accentPrice: '#f59e0b',
        }
    },
    {
        name: "Crepúsculo",
        colors: {
            background: '#0f0119',
            foreground: '#f3e8ff',
            card: '#1e0c2e',
            cardForeground: '#f3e8ff',
            popover: '#140521',
            popoverForeground: '#f3e8ff',
            primary: '#c084fc',
            primaryForeground: '#0f0119',
            secondary: '#3b1c55',
            secondaryForeground: '#f3e8ff',
            muted: '#3b1c55',
            mutedForeground: '#a881d2',
            accent: '#a855f7',
            accentForeground: '#f3e8ff',
            destructive: '#f43f5e',
            destructiveForeground: '#f3e8ff',
            border: '#3b1c55',
            input: '#1e0c2e',
            ring: '#c084fc',
            cacambaForeground: '#e9d5ff',
            accentPrice: '#facc15',
        }
    },
];
