import type { ThemeHex } from '@/hooks/use-theme';

export interface ThemePreset {
    name: string;
    colors: ThemeHex;
}

export const defaultTheme: ThemePreset = {
    name: "Padrão (Escuro)",
    colors: {
        background: '#191A1B',
        foreground: '#FAFAFA',
        card: '#131415',
        cardForeground: '#FAFAFA',
        popover: '#0F1011',
        popoverForeground: '#FAFAFA',
        primary: '#4EE1A0',
        primaryForeground: '#F6FEFB',
        secondary: '#242627',
        secondaryForeground: '#FAFAFA',
        muted: '#242627',
        mutedForeground: '#A3A6A8',
        accent: '#242627',
        accentForeground: '#FAFAFA',
        destructive: '#7F1D1D',
        destructiveForeground: '#FAFAFA',
        border: '#3F4144',
        input: '#242627',
        ring: '#4EE1A0',
        cacambaForeground: '#FAFAFA',
        accentPrice: '#FBBF24',
        settingsButtonBg: '#131415',
    }
};

export const themes: ThemePreset[] = [
    defaultTheme,
    {
        name: "Neve (Claro)",
        colors: {
            background: '#F9FAFB',
            foreground: '#111827',
            card: '#FFFFFF',
            cardForeground: '#111827',
            popover: '#FFFFFF',
            popoverForeground: '#111827',
            primary: '#2563EB',
            primaryForeground: '#FFFFFF',
            secondary: '#F3F4F6',
            secondaryForeground: '#111827',
            muted: '#F3F4F6',
            mutedForeground: '#6B7280',
            accent: '#F3F4F6',
            accentForeground: '#111827',
            destructive: '#DC2626',
            destructiveForeground: '#FFFFFF',
            border: '#E5E7EB',
            input: '#FFFFFF',
            ring: '#2563EB',
            cacambaForeground: '#111827',
            accentPrice: '#F59E0B',
            settingsButtonBg: '#FFFFFF',
        }
    },
    {
        name: "Cyberpunk Neon",
        colors: {
            background: '#0d0221',
            foreground: '#f0f0f0',
            card: '#1a0c36',
            cardForeground: '#f0f0f0',
            popover: '#100529',
            popoverForeground: '#f0f0f0',
            primary: '#00f6ff',
            primaryForeground: '#0d0221',
            secondary: '#241440',
            secondaryForeground: '#f0f0f0',
            muted: '#241440',
            mutedForeground: '#a09ca8',
            accent: '#ff00ff',
            accentForeground: '#f0f0f0',
            destructive: '#ff003c',
            destructiveForeground: '#0d0221',
            border: '#3c2b5c',
            input: '#241440',
            ring: '#00f6ff',
            cacambaForeground: '#00f6ff',
            accentPrice: '#ff00ff',
            settingsButtonBg: '#1a0c36',
        }
    },
    {
        name: "Menta Fresca",
        colors: {
            background: '#f0fdf4',
            foreground: '#1e293b',
            card: '#ffffff',
            cardForeground: '#1e293b',
            popover: '#ffffff',
            popoverForeground: '#1e293b',
            primary: '#10b981',
            primaryForeground: '#ffffff',
            secondary: '#ecfdf5',
            secondaryForeground: '#1e293b',
            muted: '#f1f5f9',
            mutedForeground: '#64748b',
            accent: '#d1fae5',
            accentForeground: '#065f46',
            destructive: '#ef4444',
            destructiveForeground: '#ffffff',
            border: '#e2e8f0',
            input: '#ffffff',
            ring: '#10b981',
            cacambaForeground: '#065f46',
            accentPrice: '#f59e0b',
            settingsButtonBg: '#ffffff',
        }
    },
    {
        name: "Oceano Profundo",
        colors: {
            background: '#0f172a',
            foreground: '#f1f5f9',
            card: '#1e293b',
            cardForeground: '#f1f5f9',
            popover: '#0f172a',
            popoverForeground: '#f1f5f9',
            primary: '#38bdf8',
            primaryForeground: '#0f172a',
            secondary: '#334155',
            secondaryForeground: '#f1f5f9',
            muted: '#334155',
            mutedForeground: '#94a3b8',
            accent: '#475569',
            accentForeground: '#f1f5f9',
            destructive: '#f43f5e',
            destructiveForeground: '#f1f5f9',
            border: '#334155',
            input: '#334155',
            ring: '#38bdf8',
            cacambaForeground: '#38bdf8',
            accentPrice: '#fbbf24',
            settingsButtonBg: '#1e293b',
        }
    },
    {
        name: "Outono Aconchegante",
        colors: {
            background: '#2a1a1f',
            foreground: '#f3e5e1',
            card: '#3b2a2f',
            cardForeground: '#f3e5e1',
            popover: '#25151a',
            popoverForeground: '#f3e5e1',
            primary: '#f97316',
            primaryForeground: '#ffffff',
            secondary: '#4d3a3f',
            secondaryForeground: '#f3e5e1',
            muted: '#4d3a3f',
            mutedForeground: '#c4b5b1',
            accent: '#6b5a5f',
            accentForeground: '#f3e5e1',
            destructive: '#ef4444',
            destructiveForeground: '#ffffff',
            border: '#4d3a3f',
            input: '#4d3a3f',
            ring: '#f97316',
            cacambaForeground: '#f97316',
            accentPrice: '#eab308',
            settingsButtonBg: '#3b2a2f',
        }
    },
    {
        name: "Lavanda Suave",
        colors: {
            background: '#f5f3ff',
            foreground: '#2e1065',
            card: '#ffffff',
            cardForeground: '#2e1065',
            popover: '#ede9fe',
            popoverForeground: '#2e1065',
            primary: '#8b5cf6',
            primaryForeground: '#ffffff',
            secondary: '#ede9fe',
            secondaryForeground: '#4c1d95',
            muted: '#ddd6fe',
            mutedForeground: '#5b21b6',
            accent: '#c4b5fd',
            accentForeground: '#3730a3',
            destructive: '#ec4899',
            destructiveForeground: '#ffffff',
            border: '#ddd6fe',
            input: '#ffffff',
            ring: '#8b5cf6',
            cacambaForeground: '#5b21b6',
            accentPrice: '#f59e0b',
            settingsButtonBg: '#ffffff',
        }
    },
    {
        name: "Grafite Industrial",
        colors: {
            background: '#18181b',
            foreground: '#fafafa',
            card: '#27272a',
            cardForeground: '#fafafa',
            popover: '#18181b',
            popoverForeground: '#fafafa',
            primary: '#fafafa',
            primaryForeground: '#18181b',
            secondary: '#3f3f46',
            secondaryForeground: '#fafafa',
            muted: '#3f3f46',
            mutedForeground: '#a1a1aa',
            accent: '#52525b',
            accentForeground: '#fafafa',
            destructive: '#ef4444',
            destructiveForeground: '#fafafa',
            border: '#3f3f46',
            input: '#3f3f46',
            ring: '#fafafa',
            cacambaForeground: '#fafafa',
            accentPrice: '#facc15',
            settingsButtonBg: '#27272a',
        }
    },
    {
        name: "Céu de Verão",
        colors: {
            background: '#f0f9ff',
            foreground: '#0c4a6e',
            card: '#ffffff',
            cardForeground: '#0c4a6e',
            popover: '#e0f2fe',
            popoverForeground: '#0c4a6e',
            primary: '#0ea5e9',
            primaryForeground: '#ffffff',
            secondary: '#e0f2fe',
            secondaryForeground: '#0891b2',
            muted: '#bae6fd',
            mutedForeground: '#0369a1',
            accent: '#7dd3fc',
            accentForeground: '#0c4a6e',
            destructive: '#f43f5e',
            destructiveForeground: '#ffffff',
            border: '#bae6fd',
            input: '#ffffff',
            ring: '#0ea5e9',
            cacambaForeground: '#0369a1',
            accentPrice: '#f97316',
            settingsButtonBg: '#ffffff',
        }
    },
    {
        name: "Drácula",
        colors: {
            background: '#282a36',
            foreground: '#f8f8f2',
            card: '#44475a',
            cardForeground: '#f8f8f2',
            popover: '#282a36',
            popoverForeground: '#f8f8f2',
            primary: '#bd93f9',
            primaryForeground: '#282a36',
            secondary: '#6272a4',
            secondaryForeground: '#f8f8f2',
            muted: '#6272a4',
            mutedForeground: '#f8f8f2',
            accent: '#ff79c6',
            accentForeground: '#282a36',
            destructive: '#ff5555',
            destructiveForeground: '#f8f8f2',
            border: '#6272a4',
            input: '#44475a',
            ring: '#bd93f9',
            cacambaForeground: '#50fa7b',
            accentPrice: '#f1fa8c',
            settingsButtonBg: '#44475a',
        }
    },
    {
        name: "Rosa Quartzo",
        colors: {
            background: '#fff1f2',
            foreground: '#500724',
            card: '#ffffff',
            cardForeground: '#500724',
            popover: '#ffe4e6',
            popoverForeground: '#500724',
            primary: '#ec4899',
            primaryForeground: '#ffffff',
            secondary: '#fce7f3',
            secondaryForeground: '#831843',
            muted: '#fbcfe8',
            mutedForeground: '#9d174d',
            accent: '#f9a8d4',
            accentForeground: '#500724',
            destructive: '#e11d48',
            destructiveForeground: '#ffffff',
            border: '#fbcfe8',
            input: '#ffffff',
            ring: '#ec4899',
            cacambaForeground: '#9d174d',
            accentPrice: '#f59e0b',
            settingsButtonBg: '#ffffff',
        }
    },
    {
        name: "Matrix",
        colors: {
            background: '#000000',
            foreground: '#00ff00',
            card: '#0a0a0a',
            cardForeground: '#00ff00',
            popover: '#000000',
            popoverForeground: '#00ff00',
            primary: '#00ff00',
            primaryForeground: '#000000',
            secondary: '#0f0f0f',
            secondaryForeground: '#00ff00',
            muted: '#1a1a1a',
            mutedForeground: '#008000',
            accent: '#1f1f1f',
            accentForeground: '#00ff00',
            destructive: '#ff0000',
            destructiveForeground: '#000000',
            border: '#003300',
            input: '#0a0a0a',
            ring: '#00ff00',
            cacambaForeground: '#ffffff',
            accentPrice: '#00ff00',
            settingsButtonBg: '#0a0a0a',
        }
    },
    {
        name: "Café Expresso",
        colors: {
            background: '#1c1611',
            foreground: '#d4c5b0',
            card: '#2c221a',
            cardForeground: '#d4c5b0',
            popover: '#16110e',
            popoverForeground: '#d4c5b0',
            primary: '#a67b5b',
            primaryForeground: '#1c1611',
            secondary: '#403229',
            secondaryForeground: '#d4c5b0',
            muted: '#403229',
            mutedForeground: '#8c7e6a',
            accent: '#594639',
            accentForeground: '#d4c5b0',
            destructive: '#993d3d',
            destructiveForeground: '#d4c5b0',
            border: '#403229',
            input: '#2c221a',
            ring: '#a67b5b',
            cacambaForeground: '#a67b5b',
            accentPrice: '#d97706',
            settingsButtonBg: '#2c221a',
        }
    },
    {
        name: "Areia do Deserto (Claro)",
        colors: {
            background: '#fdf6e3',
            foreground: '#657b83',
            card: '#f6efd5',
            cardForeground: '#586e75',
            popover: '#eee8d5',
            popoverForeground: '#586e75',
            primary: '#268bd2',
            primaryForeground: '#ffffff',
            secondary: '#eee8d5',
            secondaryForeground: '#586e75',
            muted: '#eee8d5',
            mutedForeground: '#839496',
            accent: '#d3cbb7',
            accentForeground: '#073642',
            destructive: '#dc322f',
            destructiveForeground: '#ffffff',
            border: '#eee8d5',
            input: '#fdf6e3',
            ring: '#268bd2',
            cacambaForeground: '#073642',
            accentPrice: '#b58900',
            settingsButtonBg: '#f6efd5',
        }
    },
    {
        name: "Floresta Sombria",
        colors: {
            background: '#1a202c',
            foreground: '#e2e8f0',
            card: '#2d3748',
            cardForeground: '#e2e8f0',
            popover: '#1a202c',
            popoverForeground: '#e2e8f0',
            primary: '#48bb78',
            primaryForeground: '#1a202c',
            secondary: '#4a5568',
            secondaryForeground: '#e2e8f0',
            muted: '#4a5568',
            mutedForeground: '#a0aec0',
            accent: '#718096',
            accentForeground: '#e2e8f0',
            destructive: '#e53e3e',
            destructiveForeground: '#e2e8f0',
            border: '#4a5568',
            input: '#2d3748',
            ring: '#48bb78',
            cacambaForeground: '#68d391',
            accentPrice: '#f6ad55',
            settingsButtonBg: '#2d3748',
        }
    },
    {
        name: "Pêssego e Creme",
        colors: {
            background: '#fff7f0',
            foreground: '#432818',
            card: '#ffffff',
            cardForeground: '#432818',
            popover: '#ffeadb',
            popoverForeground: '#432818',
            primary: '#ff8a5b',
            primaryForeground: '#432818',
            secondary: '#ffeadb',
            secondaryForeground: '#432818',
            muted: '#fdeadd',
            mutedForeground: '#995a3b',
            accent: '#fddfc8',
            accentForeground: '#432818',
            destructive: '#ef4444',
            destructiveForeground: '#ffffff',
            border: '#fddfc8',
            input: '#ffffff',
            ring: '#ff8a5b',
            cacambaForeground: '#995a3b',
            accentPrice: '#f59e0b',
            settingsButtonBg: '#ffffff',
        }
    },
    {
        name: "Ártico (Claro)",
        colors: {
            background: '#f9fafb',
            foreground: '#1f2937',
            card: '#ffffff',
            cardForeground: '#1f2937',
            popover: '#f3f4f6',
            popoverForeground: '#1f2937',
            primary: '#3b82f6',
            primaryForeground: '#ffffff',
            secondary: '#e5e7eb',
            secondaryForeground: '#1f2937',
            muted: '#f3f4f6',
            mutedForeground: '#6b7280',
            accent: '#dbeafe',
            accentForeground: '#1e40af',
            destructive: '#ef4444',
            destructiveForeground: '#ffffff',
            border: '#d1d5db',
            input: '#ffffff',
            ring: '#3b82f6',
            cacambaForeground: '#1e3a8a',
            accentPrice: '#f59e0b',
            settingsButtonBg: '#ffffff',
        }
    },
    {
        name: "Vampiro",
        colors: {
            background: '#1d1f21',
            foreground: '#c5c8c6',
            card: '#282a2e',
            cardForeground: '#c5c8c6',
            popover: '#1d1f21',
            popoverForeground: '#c5c8c6',
            primary: '#cc6666',
            primaryForeground: '#1d1f21',
            secondary: '#373b41',
            secondaryForeground: '#c5c8c6',
            muted: '#373b41',
            mutedForeground: '#969896',
            accent: '#b294bb',
            accentForeground: '#1d1f21',
            destructive: '#a54242',
            destructiveForeground: '#c5c8c6',
            border: '#373b41',
            input: '#282a2e',
            ring: '#cc6666',
            cacambaForeground: '#81a2be',
            accentPrice: '#f0c674',
            settingsButtonBg: '#282a2e',
        }
    },
    {
        name: "Cítrico",
        colors: {
            background: '#f7fee7',
            foreground: '#365314',
            card: '#ffffff',
            cardForeground: '#365314',
            popover: '#f0fdf4',
            popoverForeground: '#365314',
            primary: '#84cc16',
            primaryForeground: '#365314',
            secondary: '#dcfce7',
            secondaryForeground: '#365314',
            muted: '#ecfccb',
            mutedForeground: '#4d7c0f',
            accent: '#d9f99d',
            accentForeground: '#365314',
            destructive: '#ef4444',
            destructiveForeground: '#ffffff',
            border: '#d9f99d',
            input: '#ffffff',
            ring: '#84cc16',
            cacambaForeground: '#4d7c0f',
            accentPrice: '#f59e0b',
            settingsButtonBg: '#ffffff',
        }
    },
    {
        name: "Ardósia Escura",
        colors: {
            background: '#020617',
            foreground: '#e2e8f0',
            card: '#0f172a',
            cardForeground: '#e2e8f0',
            popover: '#020617',
            popoverForeground: '#e2e8f0',
            primary: '#f8fafc',
            primaryForeground: '#020617',
            secondary: '#1e293b',
            secondaryForeground: '#e2e8f0',
            muted: '#1e293b',
            mutedForeground: '#94a3b8',
            accent: '#334155',
            accentForeground: '#e2e8f0',
            destructive: '#be123c',
            destructiveForeground: '#e2e8f0',
            border: '#1e293b',
            input: '#0f172a',
            ring: '#f8fafc',
            cacambaForeground: '#64748b',
            accentPrice: '#ca8a04',
            settingsButtonBg: '#0f172a',
        }
    },
    {
        name: "Abelha",
        colors: {
            background: '#fffbeb',
            foreground: '#422006',
            card: '#ffffff',
            cardForeground: '#422006',
            popover: '#fef3c7',
            popoverForeground: '#422006',
            primary: '#f59e0b',
            primaryForeground: '#422006',
            secondary: '#fef3c7',
            secondaryForeground: '#422006',
            muted: '#fef9c3',
            mutedForeground: '#78350f',
            accent: '#fde68a',
            accentForeground: '#422006',
            destructive: '#ef4444',
            destructiveForeground: '#ffffff',
            border: '#fde68a',
            input: '#ffffff',
            ring: '#f59e0b',
            cacambaForeground: '#78350f',
            accentPrice: '#ea580c',
            settingsButtonBg: '#ffffff',
        }
    },
    {
        name: "Tokio Night",
        colors: {
            background: '#1a1b26',
            foreground: '#a9b1d6',
            card: '#24283b',
            cardForeground: '#a9b1d6',
            popover: '#1f2335',
            popoverForeground: '#a9b1d6',
            primary: '#7aa2f7',
            primaryForeground: '#1a1b26',
            secondary: '#414868',
            secondaryForeground: '#a9b1d6',
            muted: '#414868',
            mutedForeground: '#565f89',
            accent: '#bb9af7',
            accentForeground: '#1a1b26',
            destructive: '#f7768e',
            destructiveForeground: '#1a1b26',
            border: '#414868',
            input: '#24283b',
            ring: '#7aa2f7',
            cacambaForeground: '#e0af68',
            accentPrice: '#ff9e64',
            settingsButtonBg: '#24283b',
        }
    },
    {
        name: "Material You (Claro)",
        colors: {
            background: '#fffbfe',
            foreground: '#1c1b1f',
            card: '#f4eff4',
            cardForeground: '#1c1b1f',
            popover: '#e8e0e9',
            popoverForeground: '#1c1b1f',
            primary: '#6750a4',
            primaryForeground: '#ffffff',
            secondary: '#e8def8',
            secondaryForeground: '#1d192b',
            muted: '#e8e0e9',
            mutedForeground: '#49454f',
            accent: '#fddd82',
            accentForeground: '#1c1b1f',
            destructive: '#b3261e',
            destructiveForeground: '#ffffff',
            border: '#cac4d0',
            input: '#f4eff4',
            ring: '#6750a4',
            cacambaForeground: '#4a4458',
            accentPrice: '#7d5260',
            settingsButtonBg: '#f4eff4',
        }
    },
    {
        name: "Material You (Escuro)",
        colors: {
            background: '#1c1b1f',
            foreground: '#e6e1e5',
            card: '#2b2930',
            cardForeground: '#e6e1e5',
            popover: '#25232a',
            popoverForeground: '#e6e1e5',
            primary: '#d0bcff',
            primaryForeground: '#381e72',
            secondary: '#ccc2dc',
            secondaryForeground: '#332d41',
            muted: '#312d35',
            mutedForeground: '#958f99',
            accent: '#fddd82',
            accentForeground: '#3e2e00',
            destructive: '#f2b8b5',
            destructiveForeground: '#601410',
            border: '#49454f',
            input: '#2b2930',
            ring: '#d0bcff',
            cacambaForeground: '#cac4d0',
            accentPrice: '#f7b1b0',
            settingsButtonBg: '#2b2930',
        }
    },
    {
        name: "Nord",
        colors: {
            background: '#2e3440',
            foreground: '#d8dee9',
            card: '#3b4252',
            cardForeground: '#d8dee9',
            popover: '#2e3440',
            popoverForeground: '#d8dee9',
            primary: '#88c0d0',
            primaryForeground: '#2e3440',
            secondary: '#434c5e',
            secondaryForeground: '#d8dee9',
            muted: '#4c566a',
            mutedForeground: '#d8dee9',
            accent: '#81a1c1',
            accentForeground: '#2e3440',
            destructive: '#bf616a',
            destructiveForeground: '#d8dee9',
            border: '#4c566a',
            input: '#3b4252',
            ring: '#88c0d0',
            cacambaForeground: '#a3be8c',
            accentPrice: '#ebcb8b',
            settingsButtonBg: '#3b4252',
        }
    },
    {
        name: "Aurora",
        colors: {
            background: '#f9fafa',
            foreground: '#374151',
            card: '#ffffff',
            cardForeground: '#374151',
            popover: '#ffffff',
            popoverForeground: '#374151',
            primary: '#6366f1',
            primaryForeground: '#ffffff',
            secondary: '#f3f4f6',
            secondaryForeground: '#374151',
            muted: '#e5e7eb',
            mutedForeground: '#6b7280',
            accent: '#eef2ff',
            accentForeground: '#4338ca',
            destructive: '#ef4444',
            destructiveForeground: '#ffffff',
            border: '#e5e7eb',
            input: '#ffffff',
            ring: '#6366f1',
            cacambaForeground: '#4f46e5',
            accentPrice: '#f59e0b',
            settingsButtonBg: '#ffffff',
        }
    },
    {
        name: "Crepúsculo",
        colors: {
            background: '#0f0119',
            foreground: '#f3e8ff',
            card: '#1e0c2e',
            cardForeground: '#f3e8ff',
            popover: '#140521',
            popoverForeground: '#f3e8ff',
            primary: '#c084fc',
            primaryForeground: '#0f0119',
            secondary: '#3b1c55',
            secondaryForeground: '#f3e8ff',
            muted: '#3b1c55',
            mutedForeground: '#a881d2',
            accent: '#a855f7',
            accentForeground: '#f3e8ff',
            destructive: '#f43f5e',
            destructiveForeground: '#f3e8ff',
            border: '#3b1c55',
            input: '#1e0c2e',
            ring: '#c084fc',
            cacambaForeground: '#e9d5ff',
            accentPrice: '#facc15',
            settingsButtonBg: '#1e0c2e',
        }
    },
    {
        name: "Cinza: Carvão",
        colors: {
            background: '#141414',
            foreground: '#f1f1f1',
            card: '#1f1f1f',
            cardForeground: '#f1f1f1',
            popover: '#101010',
            popoverForeground: '#f1f1f1',
            primary: '#34d399',
            primaryForeground: '#141414',
            secondary: '#2a2a2a',
            secondaryForeground: '#f1f1f1',
            muted: '#2a2a2a',
            mutedForeground: '#a0a0a0',
            accent: '#3a3a3a',
            accentForeground: '#f1f1f1',
            destructive: '#ef4444',
            destructiveForeground: '#f1f1f1',
            border: '#3a3a3a',
            input: '#2a2a2a',
            ring: '#34d399',
            cacambaForeground: '#ffffff',
            accentPrice: '#fbbf24',
            settingsButtonBg: '#1f1f1f',
        }
    },
    {
        name: "Cinza: Concreto",
        colors: {
            background: '#f3f4f6',
            foreground: '#111827',
            card: '#ffffff',
            cardForeground: '#111827',
            popover: '#ffffff',
            popoverForeground: '#111827',
            primary: '#60a5fa',
            primaryForeground: '#ffffff',
            secondary: '#e5e7eb',
            secondaryForeground: '#111827',
            muted: '#e5e7eb',
            mutedForeground: '#6b7280',
            accent: '#d1d5db',
            accentForeground: '#111827',
            destructive: '#ef4444',
            destructiveForeground: '#ffffff',
            border: '#d1d5db',
            input: '#ffffff',
            ring: '#60a5fa',
            cacambaForeground: '#111827',
            accentPrice: '#f97316',
            settingsButtonBg: '#ffffff',
        }
    },
    {
        name: "Cinza: Ardósia",
        colors: {
            background: '#262626',
            foreground: '#e5e5e5',
            card: '#333333',
            cardForeground: '#e5e5e5',
            popover: '#1a1a1a',
            popoverForeground: '#e5e5e5',
            primary: '#fafafa',
            primaryForeground: '#262626',
            secondary: '#404040',
            secondaryForeground: '#e5e5e5',
            muted: '#404040',
            mutedForeground: '#a3a3a3',
            accent: '#525252',
            accentForeground: '#e5e5e5',
            destructive: '#dc2626',
            destructiveForeground: '#e5e5e5',
            border: '#525252',
            input: '#404040',
            ring: '#fafafa',
            cacambaForeground: '#ffffff',
            accentPrice: '#eab308',
            settingsButtonBg: '#333333',
        }
    },
    {
        name: "Cinza: Platina",
        colors: {
            background: '#e5e7eb',
            foreground: '#1f2937',
            card: '#f9fafb',
            cardForeground: '#1f2937',
            popover: '#f9fafb',
            popoverForeground: '#1f2937',
            primary: '#4f46e5',
            primaryForeground: '#ffffff',
            secondary: '#d1d5db',
            secondaryForeground: '#1f2937',
            muted: '#d1d5db',
            mutedForeground: '#4b5563',
            accent: '#9ca3af',
            accentForeground: '#1f2937',
            destructive: '#be123c',
            destructiveForeground: '#ffffff',
            border: '#9ca3af',
            input: '#f9fafb',
            ring: '#4f46e5',
            cacambaForeground: '#111827',
            accentPrice: '#f59e0b',
            settingsButtonBg: '#f9fafb',
        }
    },
    {
        name: "Cinza: Aço Escovado",
        colors: {
            background: '#4b5563',
            foreground: '#f9fafb',
            card: '#6b7280',
            cardForeground: '#f9fafb',
            popover: '#4b5563',
            popoverForeground: '#f9fafb',
            primary: '#ec4899',
            primaryForeground: '#ffffff',
            secondary: '#9ca3af',
            secondaryForeground: '#f9fafb',
            muted: '#9ca3af',
            mutedForeground: '#e5e7eb',
            accent: '#d1d5db',
            accentForeground: '#1f2937',
            destructive: '#fca5a5',
            destructiveForeground: '#1f2937',
            border: '#9ca3af',
            input: '#6b7280',
            ring: '#ec4899',
            cacambaForeground: '#ffffff',
            accentPrice: '#facc15',
            settingsButtonBg: '#6b7280',
        }
    },
    {
        name: "Cinza: Névoa",
        colors: {
            background: '#fafafa',
            foreground: '#262626',
            card: '#ffffff',
            cardForeground: '#262626',
            popover: '#f5f5f5',
            popoverForeground: '#262626',
            primary: '#8b5cf6',
            primaryForeground: '#ffffff',
            secondary: '#f5f5f5',
            secondaryForeground: '#262626',
            muted: '#e5e5e5',
            mutedForeground: '#737373',
            accent: '#d4d4d4',
            accentForeground: '#262626',
            destructive: '#ef4444',
            destructiveForeground: '#ffffff',
            border: '#d4d4d4',
            input: '#ffffff',
            ring: '#8b5cf6',
            cacambaForeground: '#171717',
            accentPrice: '#f59e0b',
            settingsButtonBg: '#ffffff',
        }
    },
    {
        name: "Cinza: Ônix",
        colors: {
            background: '#0a0a0a',
            foreground: '#e0e0e0',
            card: '#1a1a1a',
            cardForeground: '#e0e0e0',
            popover: '#000000',
            popoverForeground: '#e0e0e0',
            primary: '#fde047',
            primaryForeground: '#0a0a0a',
            secondary: '#2c2c2c',
            secondaryForeground: '#e0e0e0',
            muted: '#2c2c2c',
            mutedForeground: '#9e9e9e',
            accent: '#424242',
            accentForeground: '#e0e0e0',
            destructive: '#b71c1c',
            destructiveForeground: '#e0e0e0',
            border: '#424242',
            input: '#1a1a1a',
            ring: '#fde047',
            cacambaForeground: '#ffffff',
            accentPrice: '#f59e0b',
            settingsButtonBg: '#1a1a1a',
        }
    },
    {
        name: "Cinza: Pedra",
        colors: {
            background: '#d6d3d1',
            foreground: '#292524',
            card: '#e7e5e4',
            cardForeground: '#292524',
            popover: '#d6d3d1',
            popoverForeground: '#292524',
            primary: '#059669',
            primaryForeground: '#ffffff',
            secondary: '#e7e5e4',
            secondaryForeground: '#292524',
            muted: '#f5f5f4',
            mutedForeground: '#78716c',
            accent: '#d6d3d1',
            accentForeground: '#292524',
            destructive: '#c2410c',
            destructiveForeground: '#ffffff',
            border: '#a8a29e',
            input: '#e7e5e4',
            ring: '#059669',
            cacambaForeground: '#1c1917',
            accentPrice: '#f59e0b',
            settingsButtonBg: '#e7e5e4',
        }
    },
    {
        name: "Cinza: Zinco",
        colors: {
            background: '#3f3f46',
            foreground: '#d4d4d8',
            card: '#52525b',
            cardForeground: '#d4d4d8',
            popover: '#27272a',
            popoverForeground: '#d4d4d8',
            primary: '#a3e635',
            primaryForeground: '#3f3f46',
            secondary: '#71717a',
            secondaryForeground: '#d4d4d8',
            muted: '#71717a',
            mutedForeground: '#a1a1aa',
            accent: '#a1a1aa',
            accentForeground: '#d4d4d8',
            destructive: '#be123c',
            destructiveForeground: '#d4d4d8',
            border: '#71717a',
            input: '#52525b',
            ring: '#a3e635',
            cacambaForeground: '#ffffff',
            accentPrice: '#fbbf24',
            settingsButtonBg: '#52525b',
        }
    },
    {
        name: "Cinza: Nuvem",
        colors: {
            background: '#f0f0f0',
            foreground: '#1e1e1e',
            card: '#ffffff',
            cardForeground: '#1e1e1e',
            popover: '#f5f5f5',
            popoverForeground: '#1e1e1e',
            primary: '#d946ef',
            primaryForeground: '#ffffff',
            secondary: '#e4e4e4',
            secondaryForeground: '#1e1e1e',
            muted: '#e4e4e4',
            mutedForeground: '#7a7a7a',
            accent: '#cccccc',
            accentForeground: '#1e1e1e',
            destructive: '#ef4444',
            destructiveForeground: '#ffffff',
            border: '#cccccc',
            input: '#ffffff',
            ring: '#d946ef',
            cacambaForeground: '#1e1e1e',
            accentPrice: '#f59e0b',
            settingsButtonBg: '#ffffff',
        }
    },
    {
        name: "Cinza: Chumbo",
        colors: {
            background: '#1f2937',
            foreground: '#d1d5db',
            card: '#374151',
            cardForeground: '#d1d5db',
            popover: '#111827',
            popoverForeground: '#d1d5db',
            primary: '#f9fafb',
            primaryForeground: '#1f2937',
            secondary: '#4b5563',
            secondaryForeground: '#d1d5db',
            muted: '#4b5563',
            mutedForeground: '#9ca3af',
            accent: '#6b7280',
            accentForeground: '#d1d5db',
            destructive: '#991b1b',
            destructiveForeground: '#d1d5db',
            border: '#6b7280',
            input: '#374151',
            ring: '#f9fafb',
            cacambaForeground: '#ffffff',
            accentPrice: '#f59e0b',
            settingsButtonBg: '#374151',
        }
    },
    {
        name: "Cinza: Gelo",
        colors: {
            background: '#f9fafb',
            foreground: '#1f2937',
            card: '#ffffff',
            cardForeground: '#1f2937',
            popover: '#f9fafb',
            popoverForeground: '#1f2937',
            primary: '#14b8a6',
            primaryForeground: '#ffffff',
            secondary: '#f3f4f6',
            secondaryForeground: '#1f2937',
            muted: '#e5e7eb',
            mutedForeground: '#6b7280',
            accent: '#d1d5db',
            accentForeground: '#1f2937',
            destructive: '#dc2626',
            destructiveForeground: '#ffffff',
            border: '#d1d5db',
            input: '#ffffff',
            ring: '#14b8a6',
            cacambaForeground: '#111827',
            accentPrice: '#f59e0b',
            settingsButtonBg: '#ffffff',
        }
    },
    {
        name: "Cinza: Fóssil",
        colors: {
            background: '#e0e0e0',
            foreground: '#1c1c1c',
            card: '#eeeeee',
            cardForeground: '#1c1c1c',
            popover: '#e0e0e0',
            popoverForeground: '#1c1c1c',
            primary: '#7c3aed',
            primaryForeground: '#ffffff',
            secondary: '#f5f5f5',
            secondaryForeground: '#1c1c1c',
            muted: '#f5f5f5',
            mutedForeground: '#757575',
            accent: '#bdbdbd',
            accentForeground: '#1c1c1c',
            destructive: '#d32f2f',
            destructiveForeground: '#ffffff',
            border: '#bdbdbd',
            input: '#eeeeee',
            ring: '#7c3aed',
            cacambaForeground: '#1c1c1c',
            accentPrice: '#f9a825',
            settingsButtonBg: '#eeeeee',
        }
    },
    {
        name: "Cinza: Noturno",
        colors: {
            background: '#171717',
            foreground: '#e5e5e5',
            card: '#262626',
            cardForeground: '#e5e5e5',
            popover: '#000000',
            popoverForeground: '#e5e5e5',
            primary: '#22d3ee',
            primaryForeground: '#171717',
            secondary: '#404040',
            secondaryForeground: '#e5e5e5',
            muted: '#404040',
            mutedForeground: '#a3a3a3',
            accent: '#525252',
            accentForeground: '#e5e5e5',
            destructive: '#ef4444',
            destructiveForeground: '#e5e5e5',
            border: '#525252',
            input: '#262626',
            ring: '#22d3ee',
            cacambaForeground: '#ffffff',
            accentPrice: '#fde047',
            settingsButtonBg: '#262626',
        }
    },
    {
        name: "Cinza: Urbano",
        colors: {
            background: '#d4d4d8',
            foreground: '#18181b',
            card: '#e4e4e7',
            cardForeground: '#18181b',
            popover: '#d4d4d8',
            popoverForeground: '#18181b',
            primary: '#db2777',
            primaryForeground: '#ffffff',
            secondary: '#e4e4e7',
            secondaryForeground: '#18181b',
            muted: '#f4f4f5',
            mutedForeground: '#71717a',
            accent: '#a1a1aa',
            accentForeground: '#18181b',
            destructive: '#be185d',
            destructiveForeground: '#ffffff',
            border: '#a1a1aa',
            input: '#e4e4e7',
            ring: '#db2777',
            cacambaForeground: '#18181b',
            accentPrice: '#f97316',
            settingsButtonBg: '#e4e4e7',
        }
    },
    {
        name: "Cinza: Monocromático",
        colors: {
            background: '#000000',
            foreground: '#ffffff',
            card: '#1c1c1c',
            cardForeground: '#ffffff',
            popover: '#000000',
            popoverForeground: '#ffffff',
            primary: '#ffffff',
            primaryForeground: '#000000',
            secondary: '#333333',
            secondaryForeground: '#ffffff',
            muted: '#333333',
            mutedForeground: '#b0b0b0',
            accent: '#4d4d4d',
            accentForeground: '#ffffff',
            destructive: '#ff4d4d',
            destructiveForeground: '#000000',
            border: '#4d4d4d',
            input: '#1c1c1c',
            ring: '#ffffff',
            cacambaForeground: '#ffffff',
            accentPrice: '#b0b0b0',
            settingsButtonBg: '#1c1c1c',
        }
    },
    {
        name: "Cinza: Minimalista Claro",
        colors: {
            background: '#ffffff',
            foreground: '#000000',
            card: '#f5f5f5',
            cardForeground: '#000000',
            popover: '#f5f5f5',
            popoverForeground: '#000000',
            primary: '#000000',
            primaryForeground: '#ffffff',
            secondary: '#e8e8e8',
            secondaryForeground: '#000000',
            muted: '#e8e8e8',
            mutedForeground: '#6e6e6e',
            accent: '#dcdcdc',
            accentForeground: '#000000',
            destructive: '#e60000',
            destructiveForeground: '#ffffff',
            border: '#dcdcdc',
            input: '#f5f5f5',
            ring: '#000000',
            cacambaForeground: '#000000',
            accentPrice: '#6e6e6e',
            settingsButtonBg: '#f5f5f5',
        }
    },
    {
        name: "Cinza: Trovão",
        colors: {
            background: '#23272a',
            foreground: '#ffffff',
            card: '#2c2f33',
            cardForeground: '#ffffff',
            popover: '#1e2124',
            popoverForeground: '#ffffff',
            primary: '#7289da',
            primaryForeground: '#ffffff',
            secondary: '#40444b',
            secondaryForeground: '#ffffff',
            muted: '#40444b',
            mutedForeground: '#99aab5',
            accent: '#5865f2',
            accentForeground: '#ffffff',
            destructive: '#ed4245',
            destructiveForeground: '#ffffff',
            border: '#40444b',
            input: '#2c2f33',
            ring: '#7289da',
            cacambaForeground: '#ffffff',
            accentPrice: '#f1c40f',
            settingsButtonBg: '#2c2f33',
        }
    },
    {
        name: "Cinza: Cimento Queimado",
        colors: {
            background: '#bebebe',
            foreground: '#1e1e1e',
            card: '#cdcdcd',
            cardForeground: '#1e1e1e',
            popover: '#bebebe',
            popoverForeground: '#1e1e1e',
            primary: '#e67e22',
            primaryForeground: '#ffffff',
            secondary: '#d9d9d9',
            secondaryForeground: '#1e1e1e',
            muted: '#e8e8e8',
            mutedForeground: '#636363',
            accent: '#b3b3b3',
            accentForeground: '#1e1e1e',
            destructive: '#c0392b',
            destructiveForeground: '#ffffff',
            border: '#a6a6a6',
            input: '#cdcdcd',
            ring: '#e67e22',
            cacambaForeground: '#1e1e1e',
            accentPrice: '#f39c12',
            settingsButtonBg: '#cdcdcd',
        }
    },
    {
        name: "Cinza: Estanho",
        colors: {
            background: '#9e9e9e',
            foreground: '#121212',
            card: '#b0b0b0',
            cardForeground: '#121212',
            popover: '#9e9e9e',
            popoverForeground: '#121212',
            primary: '#29b6f6',
            primaryForeground: '#ffffff',
            secondary: '#c1c1c1',
            secondaryForeground: '#121212',
            muted: '#d2d2d2',
            mutedForeground: '#545454',
            accent: '#8c8c8c',
            accentForeground: '#121212',
            destructive: '#f44336',
            destructiveForeground: '#ffffff',
            border: '#8c8c8c',
            input: '#b0b0b0',
            ring: '#29b6f6',
            cacambaForeground: '#121212',
            accentPrice: '#ffb300',
            settingsButtonBg: '#b0b0b0',
        }
    },
    {
        name: "Cinza: Ferro",
        colors: {
            background: '#2c3e50',
            foreground: '#ecf0f1',
            card: '#34495e',
            cardForeground: '#ecf0f1',
            popover: '#2c3e50',
            popoverForeground: '#ecf0f1',
            primary: '#1abc9c',
            primaryForeground: '#ffffff',
            secondary: '#5d6d7e',
            secondaryForeground: '#ecf0f1',
            muted: '#5d6d7e',
            mutedForeground: '#bdc3c7',
            accent: '#7f8c8d',
            accentForeground: '#ecf0f1',
            destructive: '#e74c3c',
            destructiveForeground: '#ffffff',
            border: '#5d6d7e',
            input: '#34495e',
            ring: '#1abc9c',
            cacambaForeground: '#ffffff',
            accentPrice: '#f39c12',
            settingsButtonBg: '#34495e',
        }
    },
    {
        name: "Cinza: Mercúrio",
        colors: {
            background: '#e0e0e0',
            foreground: '#212121',
            card: '#f5f5f5',
            cardForeground: '#212121',
            popover: '#e0e0e0',
            popoverForeground: '#212121',
            primary: '#9c27b0',
            primaryForeground: '#ffffff',
            secondary: '#f5f5f5',
            secondaryForeground: '#212121',
            muted: '#eeeeee',
            mutedForeground: '#757575',
            accent: '#bdbdbd',
            accentForeground: '#212121',
            destructive: '#e53935',
            destructiveForeground: '#ffffff',
            border: '#bdbdbd',
            input: '#f5f5f5',
            ring: '#9c27b0',
            cacambaForeground: '#212121',
            accentPrice: '#ffb300',
            settingsButtonBg: '#f5f5f5',
        }
    },
    {
        name: "Cinza: Granito",
        colors: {
            background: '#616161',
            foreground: '#f5f5f5',
            card: '#757575',
            cardForeground: '#f5f5f5',
            popover: '#424242',
            popoverForeground: '#f5f5f5',
            primary: '#ffca28',
            primaryForeground: '#424242',
            secondary: '#8d8d8d',
            secondaryForeground: '#f5f5f5',
            muted: '#8d8d8d',
            mutedForeground: '#e0e0e0',
            accent: '#a4a4a4',
            accentForeground: '#f5f5f5',
            destructive: '#d32f2f',
            destructiveForeground: '#f5f5f5',
            border: '#8d8d8d',
            input: '#757575',
            ring: '#ffca28',
            cacambaForeground: '#ffffff',
            accentPrice: '#f57c00',
            settingsButtonBg: '#757575',
        }
    },
    {
        name: "Cinza: Industrial Claro",
        colors: {
            background: '#eceff1',
            foreground: '#263238',
            card: '#ffffff',
            cardForeground: '#263238',
            popover: '#eceff1',
            popoverForeground: '#263238',
            primary: '#00897b',
            primaryForeground: '#ffffff',
            secondary: '#cfd8dc',
            secondaryForeground: '#263238',
            muted: '#cfd8dc',
            mutedForeground: '#546e7a',
            accent: '#b0bec5',
            accentForeground: '#263238',
            destructive: '#d84315',
            destructiveForeground: '#ffffff',
            border: '#b0bec5',
            input: '#ffffff',
            ring: '#00897b',
            cacambaForeground: '#263238',
            accentPrice: '#fdd835',
            settingsButtonBg: '#ffffff',
        }
    }
];

    